"""add erorr_code field in table attendance_logs

Revision ID: 2fe43803b0d3
Revises: 4c23db2ab845
Create Date: 2025-12-05 11:53:53.625193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe43803b0d3'
down_revision = '4c23db2ab845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_code', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.drop_column('error_code')

    # ### end Alembic commands ###
