"""add log attendance_logs table

Revision ID: 4c23db2ab845
Revises: 9567bfbf07db
Create Date: 2025-12-04 08:33:06.414588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c23db2ab845'
down_revision = '9567bfbf07db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfid_uid', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_logs_rfid_uid'), ['rfid_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_logs_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_attendance_logs_rfid_uid'))

    op.drop_table('attendance_logs')
    # ### end Alembic commands ###
